title: Heidi
email: comite-heidi@googlegroups.com
description: > # this means to ignore newlines until "show_excerpts:"
  Troupe d'improvisation théatrale de l'UNIL et EPFL

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d %b %Y"

  social_links:
    github:  heidi-impro
    instagram: heidimpro

header_pages:
 - contact.md

remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
